### ISSUE TITLE
9. Architectural decisions

### ISSUE THREAD

**Issue by marcosmatilla** [Arquisoft/viade_es5c#13]

**Comment by marcosmatilla** [comment]
Te dejo por aquí los puntos para que hagas de este punto de la documentación.
Backend -> (node, js)
Data storage -> (SOLID)
Documentation -> (Ruby)
Hecha un vistazo a ver, por si se me pasa algo de lo que hablar.

**Comment by marcosmatilla** [comment]
El punto de Data Storage ya está.

**Comment by marcosmatilla** [comment]
Acuérdate de hacerlo en la rama 'feature_arc42_09_architectural_decisions'. Queda tu parte.

**Comment by ghost** [comment]
De la parte de documentación no sabía muy bien que poner, porque tampoco estoy seguro de que sea un tema de arquitectura.

**Comment by marcosmatilla** [comment]
Lo que veas, yo entendí como que en este campo iban las decisiones que habíamos tomando de cara al desarrollo general del proyecto.
