### ISSUE TITLE
Login y logout

### ISSUE THREAD

**Issue by uo258865** [Arquisoft/viade_es5c#33]

**Comment by aitorllanos99** [comment]
Ines he encontrado este codigo con jquery y la libreria rdf, por si te interesa, asi cuand esta loggeado muestra el nombre del usuario.
const FOAF = $rdf.Namespace('http://xmlns.com/foaf/0.1/');
$('#view').click(async function loadProfile() {
  // Set up a local data store and associated data fetcher
  const store = $rdf.graph();
  const fetcher = new $rdf.Fetcher(store);

  // Load the person's data into the store
  const person = $('#profile').val();
  await fetcher.load(person);

  // Display their details
  const fullName = store.any($rdf.sym(person), FOAF('name'));
  $('#fullName').text(fullName && fullName.value);
});
