### ISSUE TITLE
Cargar archivos GEOJSON, KML, GPX...

### ISSUE THREAD

**Issue by uo258865** [Arquisoft/viade_es5c#37]
Que sea posible cargar archivos que sean geojson, kml y gpx, para que puedan cargar las rutas desde su ordenador.

**Comment by uo258865** [comment]
Ya se puede geojson, queda que se pueda kml y gpx

**Comment by marcosmatilla** [comment]
Quizá te pueda servir como referencia la práctica de JS de SEW. Ejercicio 14 tarea 1.
