### ISSUE TITLE
Aplication must be cleaned 

### ISSUE THREAD

**Issue by Borjarguez** [Arquisoft/viade_es5c#40]
Extras as the game must be removed

**Comment by marcosmatilla** [comment]
Ok, received. Be careful where you delete, make sure you only delete unnecessary things. There are many others that could help us.

**Comment by Borjarguez** [comment]
Just clean innecessary interface options, code will be cleaned up later

**Comment by marcosmatilla** [comment]
For the moment do not delete classes that already existed

**Comment by Borjarguez** [comment]
Done
