### ISSUE TITLE
Friends Wrapper for the images

### ISSUE THREAD

**Issue by aitorllanos99** [Arquisoft/viade_es5c#53]

**Comment by Borjarguez** [comment]
Have you made changes or can i do it?

**Comment by aitorllanos99** [comment]
Yeah i almost finished it, i have the expectations to push it tomorrow

**Comment by aitorllanos99** [comment]
Borja i already pushed it to my branch "fixing_feature_listar_amigos" check it out, and tell me what you think about it.

Thank You.
