### ISSUE TITLE
Talking with the creator of solid Vincent

### ISSUE THREAD

**Issue by aitorllanos99** [Arquisoft/viade_es5c#69]
Here is where we are gonna put our advances in the conversation with vincent from solid for the changes that he purpose to read from the pod

**Comment by aitorllanos99** [comment]
here is the link of the conversation in the forum
https://forum.solidproject.org/t/problem-reading-files-from-the-pod/2819/12

**Comment by Borjarguez** [comment]
Great help from him ❤️
