### ISSUE TITLE
7. Deployment View

### ISSUE THREAD

**Issue by aitorllanos99** [Arquisoft/viade_es5c#9]
7 document docs, external view of the application

**Comment by aitorllanos99** [comment]
Bernardo , he hecho el login y el guardar/hacer rutas, haz tu el compartir rutas y el añadir amigo. Me encargo yo de hacer el compartir archivos y el visualizar ruta

**Comment by BernardoBegega** [comment]
vale, ya esta. Si necesitas ayuda en algo más o encuentras algún fallo avísame
